name: Reset weekly scores
on:
  schedule:
    - cron: '0 0 * * 1'   # Monday 00:00 UTC
  workflow_dispatch:        # manual test
jobs:
  reset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Empty scores.json
        run: echo '[]' > data/scores.json
      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/scores.json
          git commit -m "Weekly reset" || true
          git push
